version: 2
jobs:
  build-odkx:
    working_directory: ~/work
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install checkout requirements
          command: |
            curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
            sudo apt-get install git-lfs
            git lfs install
      - run:
          name: Checkout binaries
          command: git lfs pull
      - run:
          name: Install build requirements
          command: |
#            sudo apt-get install pngquant
#            sudo apt-get install python-enchant
            sudo pip install -r requirements.txt
      - run:
          name: Style Guide Check
          command: |
            paths=$(git diff origin/master... --name-only)
            echo $paths
            sudo python style-test.py $paths -r odkx-src
            sudo python style-test.py $paths -r shared-src
      - run:
          name: Build ODK-X Documentation
          command: make odkx-deploy
      - run:
          name: Check spelling of ODK-X Documentation
          command: make odkx-spell-check
      - run:
          name: Build LaTex of ODK-X Documentation
          command: make odkx-latex
#      - run:
#          name: Compress images
#          command: pngquant odkx-build/_images/*.png --force --ext .png --verbose
#      - store_artifacts:
#          path: odkx-build
#          destination: odkx-build
#      - persist_to_workspace:
#          root: ~/work
#          paths:
#            - odkx-build/*
#            - odkx-config/*
  
workflows:
  version: 2
  build:
    jobs:
      - build-odkx
